apiVersion: v1
kind: Service
metadata:
  name: techchallenge-update
spec:
  type: NodePort
  selector:
    app: techchallenge-update
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
