{
 "title": "dotnet-monitor dashboard",
 "description": "This dotnet-monitor dashboard is designed to show the default .NET metrics scraped using Managed Prometheus on Azure.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_runtime_working_set", "legendFormat": "Working Set" },
    { "expr": "system_runtime_gc_heap_size", "legendFormat": "GC Heap Size" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "CPU Usage" }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "OK Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, endpoint, action, code, controller) (round(increase(http_requests_received_total{code=~\"2[0-9][0-9]\"}[$__range])) > 0)",
     "legendFormat": "{{method}} /{{endpoint}} {{code}}"
    }
   ]
  },
  {
   "title": "Not OK Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint, method, code) (round(increase(http_requests_received_total{code!~\"2[0-9][0-9]\"}[$__range])) > 0)",
     "legendFormat": "{{method}} /{{endpoint}} {{code}}"
    }
   ]
  },
  {
   "title": "Avg Time Response",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint, code, action) (rate(http_request_duration_seconds_sum[$__range])) / sum by(endpoint, code, action) (rate(http_request_duration_seconds_count[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "GC Generation Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_runtime_gen_0_size", "legendFormat": "Gen 0 size" },
    { "expr": "system_runtime_gen_1_size", "legendFormat": "Gen 1 size" },
    { "expr": "system_runtime_gen_2_size", "legendFormat": "Gen 2 size" }
   ]
  }
 ]
}