apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:     
        - job_name: 'create-contact-app'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['techchallenge-create:80']
      
        - job_name: 'delete-contact-app'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['techchallenge-delete:80']
      
        - job_name: 'update-contact-app'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['techchallenge-update:80']
            
        - job_name: 'get-contact-app'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['techchallenge-get:80']