pr:
  branches:
    include:
      - develop
      - features/*

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'
  dotnetSdkVersion: '8.x'

pool:
  name: self-hosted

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK $(dotnetSdkVersion)'
            inputs:
              packageType: sdk
              version: '$(dotnetSdkVersion)'

          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: '**/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: Build Job
            inputs:
              command: 'build'
              arguments: '--no-restore --configuration $(buildConfiguration)'
              projects: '**/*.csproj'

  - stage: Test
    jobs:
      - job: Test
        steps:
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test

  - stage: Publish
    jobs:
      
      - job: OutputDirectory
        steps:
          - script: echo $(Build.ArtifactStagingDirectory)/$(buildConfiguration)

      - job: Publish
        steps:
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: publish
              projects: '**/*.csproj'
              arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
              publishWebProjects: false
              zipAfterPublish: true
          
          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: drop