apiVersion: v1
kind: Service
metadata:
  name: techchallenge-create
spec:
  type: NodePort
  selector:
    app: techchallenge-create
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010